### ISSUE TITLE
Bug: terminal background

### ISSUE THREAD

**Issue by Simon-He95** [antfu/vscode-theme-vitesse#14] opened 2022-10-30 08:23 UTC
### Describe the bug

<img width="250" alt="WeChatd0cdc386f5165f9a9551aa072477a316" src="https://user-images.githubusercontent.com/57086651/198869185-2654b78f-3ed1-43ff-8ad6-605830878880.png">
<img width="476" alt="WeChatf9f9666a940215905eea0d4de4400e34" src="https://user-images.githubusercontent.com/57086651/198869192-802374da-e1ed-44a1-96ce-d9b4cd17d368.png">

when you paste something into the terminal , this bug will happen.

### Reproduction

none

### System Info

```Shell
terminal
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-03-13 16:39
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2023-03-13 16:39 UTC

**Comment by lhz960904** [comment] 2023-05-10 15:16
I have same problem in om-my-zsh
<img width="608" alt="截屏2023-05-10 23 10 52" src="https://github.com/antfu/vscode-theme-vitesse/assets/29157111/a56384ae-568b-46b6-96ba-e9ac25619b99">

<img width="608" alt="截屏2023-05-10 23 11 29" src="https://github.com/antfu/vscode-theme-vitesse/assets/29157111/d246cf2b-d15d-4e54-b8d0-02a427039925">

**Comment by Simon-He95** [comment] 2023-05-11 13:51
> I have same problem in om-my-zsh <img alt="截屏2023-05-10 23 10 52" width="608" src="https://user-images.githubusercontent.com/29157111/237437385-a56384ae-568b-46b6-96ba-e9ac25619b99.png">
> 
> <img alt="截屏2023-05-10 23 11 29" width="608" src="https://user-images.githubusercontent.com/29157111/237437398-d246cf2b-d15d-4e54-b8d0-02a427039925.png">

I fork it and made a tweak, you can try it out with this https://marketplace.visualstudio.com/items?itemName=simonhe.theme-vitesse-colorful
